<?php

namespace ProdutoBundle\Repository;

/**
 * ProdutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdutoRepository extends \Doctrine\ORM\EntityRepository {

    public function search($find) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT p
       FROM ProdutoBundle:Produto p
       WHERE p.nome LIKE :find');
        $query->setParameter('find', '%' . $find . '%');
        return $query->getResult();
    }

}
