checkout:
    resource: "@CheckoutBundle/Controller/"
    type:     annotation
    prefix:   /checkout

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /usuario

carrinho:
    resource: "@CarrinhoBundle/Controller/"
    type:     annotation
    prefix:   /carrinho

produto:
    resource: "@ProdutoBundle/Controller/"
    type:     annotation
    prefix:   /