security:
   encoders:
       UsuarioBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12

   providers:
       customers:
            entity: { class: UsuarioBundle:Usuario, property: email }

   firewalls:
       dev:
           pattern:  ^/(_(profiler|wdt)|css|images|js)/
           security: false

       secured_area:
           pattern:    ^/
           anonymous: ~
           form_login:
               login_path:  login
               check_path:  login_check
           logout:
               path:   /usuario/logout
               target: /

   access_control:
        - { path: ^/checkout/, roles: ROLE_USER }