<?php

namespace UsuarioBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository {

    public function insert($user) {
        $em = $this->getEntityManager();
        $em->persist($user);
        $em->flush();
        
        return $user;
    }

}
